#pragma once

#include "Properties/BrushProperty.h"
#include "Properties/ColorProperty.h"
#include "Properties/CombineModeProperty.h"
#include "Properties/ContentProperty.h"
#include "Properties/FontProperty.h"
#include "Properties/FloatProperty.h"
#include "Properties/GeometryProperty.h"
#include "Properties/IntProperty.h"
#include "Properties/MarginProperty.h"
#include "Properties/MetricProperty.h"
#include "Properties/StringProperty.h"
#include "Properties/TransformProperty.h"
#include "Properties/Vec2Property.h"
#include "Properties/Vec3Property.h"
#include "Properties/Vec4Property.h"
#include "Properties/VisibilityProperty.h"